### ISSUE TITLE
1.0.0版本国服立绘替换没有生效

### ISSUE THREAD

**Issue by ScathachSkaoi** [nishuoshenme/FGOAssetsModifyTool#100]
技能和从者名正常生效替换，从者和礼装立绘替换没有生效
![Screenshot_2023-05-29-21-19-24-103_com bilibili fatego](https://github.com/hexstr/FGOAssetsModifyTool/assets/116882305/4c83bd57-2837-4bf5-9c19-bae1f2c63af5)
![Screenshot_2023-05-29-21-01-21-004_com bilibili fatego](https://github.com/hexstr/FGOAssetsModifyTool/assets/116882305/91dca3d7-5124-4af2-bf61-c47bf75be084)

**Comment by hexstr** [comment]
更新一下
