### ISSUE TITLE
打包工具打包但是没反应

### ISSUE THREAD

**Issue by SetsunaG** [nishuoshenme/FGOAssetsModifyTool#101]
大佬有空看看，打包工具之前我还用的挺好的，打包剧情文本，现在更新了新章节，今天打包的时候没反应，谢谢

![QQ截图20230609234740](https://github.com/hexstr/FGOAssetsModifyTool/assets/34825882/16ca862f-5405-452a-9e30-14c71dcb2600)

**Comment by hexstr** [comment]
路径中有空格要加双引号

**Comment by SetsunaG** [comment]
还真是 谢谢大佬
