### ISSUE TITLE
夜神模拟器下的国服宝具显示问题

### ISSUE THREAD

**Issue by SEAYuch** [nishuoshenme/FGOAssetsModifyTool#102]
夜神模拟器：7.0.5.7 Android 9
模块版本：1.0.1
在使用mstTreasureDeviceName.yaml后宝具训读和种类都变成了宝具名
![$OAMT7PBEROLONXTYURLE~O](https://github.com/hexstr/FGOAssetsModifyTool/assets/18625890/04994488-b1ac-4cbf-ab53-a59f6920e4c4)

**Comment by hexstr** [comment]
哦草，复制粘贴的时候没改过来。更新一下1.0.2

**Comment by SEAYuch** [comment]
好了
