### ISSUE TITLE
又出现了之前的问题-自定义CharaGraph丢失除满破外NarrowFigure(窄边框立绘)

### ISSUE THREAD

**Issue by royash** [nishuoshenme/FGOAssetsModifyTool#103]
文件为空的时候，不是默认图片，显示错误，普通立绘 战斗半身像正常
![HBHX)ZNVF61YKW(B7KNR C](https://github.com/hexstr/FGOAssetsModifyTool/assets/2298194/ca1134bc-eab8-427f-ad73-ac09f5bcc9e7)

**Comment by hexstr** [comment]
判断空指针只判断了满破，另一个忘记了233
![Snipaste_2023-06-21_09-54-56](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/55751bd1-3f71-4c40-976e-fd33f766019e)

下个版本更新
