### ISSUE TITLE
status未正常载入

### ISSUE THREAD

**Issue by SkylineKID** [nishuoshenme/FGOAssetsModifyTool#104]
![QQ截图20230620234349](https://github.com/hexstr/FGOAssetsModifyTool/assets/112193330/d8bb3c60-f01c-4c55-aa3e-57a0ec8546f4)
修改了1-3和灵衣的status，但是status1和2一样，灵衣显示的和status3一样，修改的灵衣status未正常载入

**Comment by hexstr** [comment]
因为灵衣的limit不是1,2,3这样，可能是11,12
![Snipaste_2023-06-21_12-52-31](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/ec8f356a-7b34-49a4-839c-be625965c2cd)

**Comment by SkylineKID** [comment]
你好，检查过其他没有灵衣的从者之后也发现了同样的问题，截图如下：


第一阶段和第二阶段的status是一样的，有灵衣的则是第三阶段和灵衣的status一致，用于替换的图片命名如下：



&nbsp; &nbsp;此致
敬礼


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "hexstr/FGOAssetsModifyTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月21日(星期三) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hexstr/FGOAssetsModifyTool] status未正常载入 (Issue #104)





 
因为灵衣的limit不是1,2,3这样，可能是11,12

**Comment by hexstr** [comment]
确实判断条件出错了，limit应该是0，1，3，然后灵衣是12，13
不过不支持加载灵衣

**Comment by SkylineKID** [comment]
好的了解，感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hexstr/FGOAssetsModifyTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月22日(星期四) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hexstr/FGOAssetsModifyTool] status未正常载入 (Issue #104)





 
确实判断条件出错了，limit应该是0，1，3，然后灵衣是12，13
 不过不支持加载灵衣
