### ISSUE TITLE
筛选界面打开速度缓慢

### ISSUE THREAD

**Issue by SkylineKID** [nishuoshenme/FGOAssetsModifyTool#105]
雷电模拟器，打开模拟器自带的高帧率模式选择144帧，未安装fps unlock，从者和礼装页面选择筛选时窗口打开缓慢，选择90帧时情况略微有一点改善但是依然较为明显

**Comment by hexstr** [comment]
这你只能等开发者修复了，虽然我不觉得一个几年没有60FPS的游戏的开发者会认为这是一个bug
