### ISSUE TITLE
安装模块后进入游戏时闪退

### ISSUE THREAD

**Issue by shatiaoaige** [nishuoshenme/FGOAssetsModifyTool#106]
![Screenshot_2023-07-26-18-03-09-579_com dp logcatapp](https://github.com/hexstr/FGOAssetsModifyTool/assets/140603659/97610523-27c6-468c-b64a-c737a8f772da)
如图是抓的log，请问这个对解决问题有帮助吗，还是要其他的什么，麻烦大佬了

**Comment by shatiaoaige** [comment]
> ![Screenshot_2023-07-26-18-03-09-579_com dp logcatapp](https://user-images.githubusercontent.com/140603659/256197599-97610523-27c6-468c-b64a-c737a8f772da.jpg) 如图是抓的log，请问这个对解决问题有帮助吗，还是要其他的什么，麻烦大佬了

补充运行环境：miui14 a13 26.1:MAGISKSU 国服，仅安装模块，未进行其他改动，尝试导入立绘文件再打开游戏，依然是闪退

**Comment by hexstr** [comment]
但这日志看起来是日服

**Comment by shatiaoaige** [comment]
确实是b服呀，而且在这之后我安装了日服，同样闪退，请问需要什么更多的信息有助于判断呢

**Comment by hexstr** [comment]
先打开Logcat Reader，点一次清除，不搜索，然后打开游戏，等闪退之后切回Logcat Reader，点保存，然后点保存Logs，最后导出，把txt文件发给我

**Comment by hexstr** [comment]
![1691111963421](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/371ba541-5113-49ed-b0a8-d05e30126c07)
