### ISSUE TITLE
更新以后在模拟器失效

### ISSUE THREAD

**Issue by kcn3388** [nishuoshenme/FGOAssetsModifyTool#107]
如题，logcat完全没有日志

**Comment by kcn3388** [comment]
![image](https://github.com/hexstr/FGOAssetsModifyTool/assets/25716090/41ffa8fa-22d1-49eb-b0a8-278357846cbf)

**Comment by royash** [comment]
你是不是更新到32位了 我刚更新也是没有 用adb更新成64的 就有了

**Comment by kcn3388** [comment]
> 你是不是更新到32位了 我刚更新也是没有 用adb更新成64的 就有了

你是对的

顺便留个档（）

```shell
adb install --abi arm64-v8a <path to apk>
```
