### ISSUE TITLE
七周年更新后从者立绘失效

### ISSUE THREAD

**Issue by akalin777** [nishuoshenme/FGOAssetsModifyTool#108]
主页头像立绘没有失效，别的我更新了最新版本也不行，反而还闪退，只能回退到0.9.4

**Comment by kcn3388** [comment]
#107

**Comment by akalin777** [comment]
> #107

是把游戏包更到64位吗，我这已经是64位的，，，安卓机不是模拟器

**Comment by Ghroth** [comment]
我用的模拟器，已经室64位的了，进去简介文本改了，但卡面还是和谐的，重装了一遍也一样，用的1.0.3模块

**Comment by hexstr** [comment]
无法复现
![Screenshot_20230804-130445_Fate_GO](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/98644597-1b32-4d30-9c50-26813902636c)

![Screenshot_20230804-130533_Fate_GO](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/226e6f14-5f8e-46b3-a454-dd679057f96c)
