### ISSUE TITLE
能否更新一下mstSvtComment.yaml

### ISSUE THREAD

**Issue by 1270207022** [nishuoshenme/FGOAssetsModifyTool#109]
如题，哪怕是日服那边的文档也行自己想办法翻译，只是想要寻找徐福和泳装武则天那一部分，实在没办法才来尝试询问的，非常感谢

**Comment by hexstr** [comment]
@1270207022 这部分确实是文档缺失，主要是上次更新还是去年，我都忘了怎么生成...

**Comment by 1270207022** [comment]
@hexstr 唉，就是看着那些个名字，多少别扭唉，可恶的国服

**Comment by hexstr** [comment]
@1270207022 国服？那可以直接用AssetToolBox一键提取MasterData，然后转换成yaml

https://github.com/hexstr/FGOAssets/releases/tag/FGOAssetToolBox

**Comment by 1270207022** [comment]
@hexstr 我试试看

**Comment by 1270207022** [comment]
@hexstr 出来的是这样的东西。。。    "svtId": 1001400,
    "id": 1,
    "priority": 0,
    "condMessage": "",
    "comment": "\u4E3A\u5B34\u6548\u529B\u7684\u9053\u58EB\uFF08\u65B9\u58EB\uFF09\u3002\n\u4F9D\u7167\u7956\u653F\u8981\u6C42\u5BFB\u6C42\u4E0D\u8001\u4E0D\u6B7B\u7075\u836F\u7684\u547D\u4EE4\uFF0C\n\u5E26\u7740\u4E09\u5343\u7AE5\u7537\u7AE5\u5973\u8E0F\u4E0A\u4E86\u524D\u5F80\u4E1C\u65B9\u4E4B\u65C5\u3002\n\u867D\u7136\u62B5\u8FBE\u4E86\u65E5\u672C\uFF0C\n\u4F46\u6700\u7EC8\u672A\u80FD\u8FD4\u56DE\u4FBF\u53BB\u4E16\u4E86\u3002\n\u65E5\u672C\u7684\u5404\u5730\u90FD\u6D41\u4F20\u7740\u65B9\u5DFF\u4F20\u8BF4\uFF0C\n\u636E\u4F20\u8BF4\u5C06\u533B\u836F\u54C1\u548C\u5236\u9676\u6280\u672F\n\u4F20\u5165\u65E5\u672C\u7684\u2026\u2026\u5C31\u662F\u5F53\u65F6\u7684\u65B9\u5DFF\u3002",
    "condType": 0,
    "condValues": [
      0
    ],
    "condValue2": 0,
    "condValue": 0,
    "scriptXuyaoshiyongjsonchulidebianliang": ""
  },
  {
    "svtId": 1001400,
    "id": 2,
    "priority": 0,
    "condMessage": "",
    "comment": "\u8EAB\u9AD8\uFF0F\u4F53\u91CD\uFF1A163cm\u00B741kg\n\u51FA\u5904\uFF1A\u53F2\u5B9E\u3001\u65B9\u5DFF\u4F20\u8BF4\u3001\u65E5\u672C\u4E66\u7EAA\u3001\u4E2D\u56FD\u795E\u8BDD\n\u5730\u57DF\uFF1A\u4E2D\u56FD\u53CA\u65E5\u672C\n\u5C5E\u6027\uFF1A\u6DF7\u6C8C\u00B7\u4E2D\u5EB8\u3000\u3000\u6027\u522B\uFF1A\u5973\u6027\n\u300C\u54CE\uFF1F\u3000\u8BB0\u5F55\u4E0A\u662F\u7537\u6027\uFF1F\u3000\u7B97\u4E86\uFF0C\u8FD9\u6837\u4E5F\u884C\uFF01\n\u3000\u53CD\u6B63\u6211\u5F88\u5FD9\uFF0C\u8FD9\u65B9\u9762\u7684\u4FEE\u6B63\u4EE5\u540E\u518D\u8BF4\uFF01\n\u3000\u9EBB\u70E6\u4E0D\u8981\u6279\u91CF\u66FF\u6362\u800C\u662F\u9010\u4E00\u4FEE\u6B63\u54E6\uFF01\u300D\n\u300C\u867D\u7136\u597D\u50CF\u5FD8\u8BB0\u4FEE\u6B63\u4E86\uFF0C\u4F46\u603B\u4E4B\u6211\u8981\u52A8\u8EAB\u4E86\n\u3000\u8FD9\u4E5F\u5C31\u65E0\u6240\u8C13\u5566\uFF01\u3000\u4E4B\u540E\u7684\u4E8B\u5C31\u62DC\u6258\u5566\uFF01\u300D",
    "condType": 9,
    "condValues": [
      1
    ],
    "condValue2": 0,
    "condValue": 0,
    "scriptXuyaoshiyongjsonchulidebianliang": ""
  },
  {
    "svtId": 1001400,
    "id": 3,
    "priority": 0,
    "condMessage": "",
    "comment": "\u6027\u683C\u00B7\u5BF9\u5FA1\u4E3B\u7684\u6001\u5EA6\n\u6027\u683C\u867D\u7136\u6709\u4E9B\u9634\u6C89\uFF0C\u4F46\u6C9F\u901A\u80FD\u529B\u610F\u5916\u5F88\u5F3A\uFF0C\n\u9664\u7956\u653F\u4EE5\u5916\uFF0C\u5BF9\u6240\u6709\u4EBA\u8BF4\u8D77\u8BDD\u6765\u90FD\u6BEB\u65E0\u987E\u5FCC\u3002\n\u53E6\u5916\uFF0C\u5BF9\u81EA\u5DF1\u7684\u5B9E\u529B\u6280\u672F\u76F8\u5F53\u81EA\u8D1F\uFF0C\n\u548C\u8868\u9762\u81EA\u5351\u7684\u6001\u5EA6\u76F8\u6BD4\uFF0C\u5B9E\u9645\u662F\u4E2A\u975E\u5E38\u81EA\u4FE1\u7684\u4EBA\u3002\n\u4F46\u5728\u8D85\u51FA\u81EA\u5DF1\u4E13\u95E8\u9886\u57DF\u7684\u6218\u6597\u65B9\u9762\uFF0C\n\u8FD8\u662F\u5F88\u80C6\u5C0F\u9000\u7F29\u7684\uFF0C\u656C\u8BF7\u8C05\u89E3\uFF08\u672C\u4EBA\u79F0\uFF09\u3002\n\n\u8FD9\u6837\u7684\u5979\u5BF9\u5FA1\u4E3B\u7684\u6001\u5EA6\u6BD4\u8F83\u8349\u7387\uFF0C\n\u4E00\u5B9A\u8981\u8BF4\u7684\u8BDD\uFF0C\u7B97\u662F\u635F\u53CB\u7C7B\u578B\u3002\n\u4F46\u9762\u5BF9\u5D07\u62DC\u7684\u96CF\u7F42\u548C\u5B9D\u7269\u822C\u7684\u739B\u4FEE\u65F6\uFF0C\n\u6001\u5EA6\u5C31\u4F1A\u9AA4\u7136\u6539\u53D8\u3002",
    "condType": 9,
    "condValues": [
      2
    ],
    "condValue2": 0,
    "condValue": 0,
    "scriptXuyaoshiyongjsonchulidebianliang": ""
  },
  {
    "svtId": 1001400,
    "id": 4,
    "priority": 0,
    "condMessage": "",
    "comment": "\u6751\u843D\u4F5C\u6210\uFF1AEX\n\u8FD9\u5DF2\u7ECF\u4E0D\u662F\u9635\u5730\u7684\u6C34\u51C6\u4E86\uFF0C\u800C\u662F\u5728\u6BEB\u65E0\u5173\u7CFB\u7684\u56FD\u5BB6\n\u5EFA\u9020\u4F9B\u8BB8\u591A\u4EBA\u7C7B\u5C45\u4F4F\u7684\u6751\u843D\u7684\u624D\u80FD\u3002\n\u5E03\u8BBE\u7ED3\u754C\u7684\u6280\u672F\u3001\u89C4\u5219\u7684\u8BBE\u8BA1\u3001\u9886\u8896\u9B45\u529B\u7684\u591A\u5BE1\u7B49\u95EE\u9898\uFF0C\n\u867D\u4E0D\u5230\u56FD\u5BB6\u7EA7\u522B\uFF0C\u4F46\u9700\u8981\u5404\u79CD\u5404\u6837\u7684\u529B\u91CF\u3002\n\n\u9053\u5177\u4F5C\u6210\uFF1AB\uFF0B\n\u7528\u9B54\u672F\u5236\u4F5C\u9053\u5177\u7684\u6280\u80FD\u3002\n\u4EC5\u5728\u4E0E\u4E0D\u8001\u4E0D\u6B7B\u76F8\u5173\u7684\u9053\u5177\u4E0A\uFF0C\u4F1A\u83B7\u5F97\u52A0\u6210\u3002\n\n\u9AD8\u7B49\u4ECE\u8005\uFF1AD\n\u4F5C\u4E3A\u4ECE\u8005\u73B0\u754C\u65F6\uFF0C\u5438\u6536\u4E86\u4E24\u4F4D\u795E\u7075\u4EE5\u56FE\u83B7\u5F97\u5F3A\u5316\u3002\n\u4E00\u4F4D\u662F\u6765\u81EA\u65E5\u672C\u7684\u5929\u76EE\u4E00\u7B87\u795E\uFF0C\n\u800C\u53E6\u4E00\u4E2A\u5219\u662F\u6765\u81EA\u4E2D\u56FD\u7684\u795E\u519C\uFF08\u4E94\u8C37\u4ED9\u5E1D\uFF09\u3002\n\u4F46\u5F52\u6839\u7ED3\u5E95\u53EA\u662F\u5438\u6536\u4E86\u4E00\u90E8\u5206\u529B\u91CF\uFF0C\n\u4E5F\u8BB8\u7528\u501F\u7528\u4E86\u4E00\u90E8\u5206\u529B\u91CF\u7684\u8BF4\u6CD5\u6BD4\u8F83\u6070\u5F53\u3002\n\u56E0\u6B64\u4E5F\u6CA1\u6709\u83B7\u5F97\u795E\u6027\u6280\u80FD\u3002\n\n\u5F31\u5316\uFF08\u96CF\u7F42\uFF09\uFF1AEX\n\u7531\u4E8E\u751F\u524D\u906D\u9047\u4E86\u96CF\u7F42\u4E00\u4E8B\uFF0C\n\u4ECE\u800C\u83B7\u5F97\u4E86\u70ED\u70C8\u7684\u4FE1\u4EF0\u3002\n\u5F53\u4E0E\u96CF\u7F42\u654C\u5BF9\u7684\u60C5\u51B5\u4E0B\uFF0C\n\u4F1A\u51FA\u73B0\u5F3A\u70C8\u7684\u5F31\u5316\uFF08\u8D1F\u9762\u6548\u679C\uFF09\u3002\n\n\u4E94\u8C37\u793C\u8D5E\uFF1AB\n\u4ECE\u5927\u9646\u5E26\u6765\u7684\u4E94\u8C37\u4E4B\u5B88\u62A4\u3002 \n\u501F\u7528\u4E86\u795E\u519C\u529B\u91CF\u4ECE\u800C\u4EA7\u751F\u7684\u6280\u80FD\u3002\n\u80FD\u56DE\u590D\u4F53\u529B\u3001\u89E3\u9664\u5F02\u5E38\u6548\u679C\u7B49\u3002\n\n\u9053\u672F\uFF08\u5916\uFF09\uFF1AA\n\u65B9\u5DFF\u662F\u9053\u672F\uFF08\u65B9\u672F\uFF09\u7684\u4E13\u5BB6\u3002\n\u4ECE\u94FA\u8BBE\u7ED3\u754C\u5230\u795B\u9664\u6076\u7075\uFF0C\u5168\u90E8\u90FD\u884C\u3002\n\u8FD9\u91CC\u63D0\u5230\u7684\u9053\u672F\u662F\u601D\u60F3\u9B54\u672F\u7684\u4E00\u79CD\uFF0C\n\u4F46\u4E0E\u601D\u60F3\u76D8\u7684\u8FDE\u63A5\u4EC5\u9650\u4E8E\u4E00\u5B9A\u8303\u56F4\u5185\uFF0C\n\u88AB\u89C6\u4F5C\u4E0E\u601D\u60F3\u952E\u7EB9\u6280\u80FD\u622A\u7136\u4E0D\u540C\u7684\u6280\u80FD\u3002\n\n\u65B9\u5DFF\u4F20\u8BF4\uFF1AC\n\u65B9\u5DFF\u4E3A\u5BFB\u627E\u4E0D\u8001\u4E0D\u6B7B\u7684\u7075\u836F\u4E1C\u6E21\u65E5\u672C\uFF0C\n\u5F53\u65F6\uFF0C\u5C06\u5404\u79CD\u6587\u5316\u5E26\u5230\u4E86\u65E5\u672C\u3002\n\u5404\u5730\u90FD\u7559\u6709\u65B9\u5DFF\u7ED9\u4E0E\u4E86\u4ED6\u4EEC\u67D0\u79CD\u4E1C\u897F\n\uFF08\u51B6\u70BC\u6280\u672F\u3001\u533B\u836F\u54C1\u3001\u9676\u827A\u7B49\uFF09\u7684\u4F20\u8BF4\uFF0C\n\u751A\u81F3\u8FD8\u5C06\u65B9\u5DFF\u796D\u7940\u5728\u795E\u793E\u4E2D\u3002\n\u57FA\u4E8E\u8FD9\u4E2A\u6280\u80FD\uFF0C\u4EE4\u5176\u5F88\u5BB9\u6613\u5438\u7EB3\u795E\u6027\u8981\u7D20\u3002",
    "condType": 9,
    "condValues": [
      3
    ],
    "condValue2": 0,
    "condValue": 0,
    "scriptXuyaoshiyongjsonchulidebianliang": ""
  },
  {
    "svtId": 1001400,
    "id": 5,
    "priority": 0,
    "condMessage": "",
    "comment": "\u300E\u6B64\u4E43\u4E0D\u8001\u4E0D\u6B7B\u7684\u7075\u836F\uFF1C\u8C0E\u8A00\uFF1E\u300F\n\u9636\u7EA7\uFF1AC\u002B\u002B\u3000\u79CD\u7C7B\uFF1A\u5BF9\u4EBA\u5B9D\u5177\n\u6709\u6548\u8303\u56F4\uFF1A1\u3000\u6700\u5927\u6355\u6349\uFF1A1\u4EBA\n\nKorenaruwafuroufushinoreiyakunari,Usodesukedo\n\u4F01\u56FE\u5C06\u4E0D\u8001\u4E0D\u6B7B\u7684\u7075\u836F\u2026\u2026\u62DF\u4F3C\u91CD\u73B0\u7684\u5B9D\u5177\u3002\n\u5F53\u7136\u65E2\u4E0D\u4F1A\u4E0D\u8001\u4E5F\u4E0D\u4F1A\u4E0D\u6B7B\u3002\n\u7ED9\u4E0E\u4ED6\u4EBA\u548C\u81EA\u8EAB\u670D\u7528\u65F6\u6548\u679C\u4E0D\u540C\uFF0C\n\u7ED9\u5BF9\u65B9\u4F7F\u7528\u65F6\u4F1A\u9020\u6210\u4F24\u5BB3\uFF0C\n\u81EA\u8EAB\u670D\u7528\u65F6\u5219\u4F1A\u4FC3\u8FDB\u56DE\u590D\u3002\n\n\u3000\u3000\u3000\u25C6\n\n\u300E\u4E0D\u6B7B\u6740\u624B\uFF1C\u672A\u81F3\uFF1E\u300F\n\u9636\u7EA7\uFF1AC\u002B\u3000\u79CD\u7C7B\uFF1A\u5BF9\u4EBA\u5B9D\u5177\n\u6709\u6548\u8303\u56F4\uFF1A1\u3000\u6700\u5927\u6355\u6349\uFF1A1\u4EBA\n\nFushigoroshi Narazu\n\u4EE5\u672A\u5B8C\u6210\u544A\u7EC8\u7684\u9690\u533F\u5B9D\u5177\u3002\n\u867D\u7136\u672A\u80FD\u5B9E\u73B0\u6740\u5BB3\u4E0D\u6B7B\uFF0C\n\u4F46\u53EF\u4EE5\u901A\u8FC7\u641C\u96C6\u5404\u79CD\u6B7B\u4EA1\uFF0C\n\u5C06\u751F\u5B58\u7684\u53EF\u80FD\u6027\u6781\u9650\u7F29\u5C0F\u6765\u4ED8\u4E0E\u751F\u7269\u6B7B\u4EA1\u3002\n\u5BF9\u539F\u672C\u5C31\u4E0E\u6B7B\u65E0\u7F18\u4E4B\u4EBA\u3001\u4E0E\u51A5\u754C\u76F8\u5173\u4E4B\u4EBA\u2026\u2026\u7B49\n\u7684\u6548\u679C\u975E\u5E38\u8584\u5F31\u3002",
    "condType": 9,
    "condValues": [
      4
    ],
    "condValue2": 0,
    "condValue": 0,
    "scriptXuyaoshiyongjsonchulidebianliang": ""
  },
  {
    "svtId": 1001400,
    "id": 6,
    "priority": 0,
    "condMessage": "",
    "comment": "\u4EBA\u7269\u5F62\u8C61\n\u88AB\u8BB0\u8F7D\u4E3A\u7537\u6027\uFF0C\u5B9E\u4E3A\u5973\u6027\u3002\n\u4F8D\u5949\u7956\u653F\uFF0C\u4F46\u67D0\u5929\u9082\u9005\u4E86\u96CF\u7F42\u3002\n\u867D\u7136\u4E3A\u96CF\u7F42\u7684\u9B45\u529B\u7740\u8FF7\uFF0C\u4F46\u4E5F\u6CE8\u610F\u5230\u4E86\u5979\u7684\u70E6\u607C\uFF0C\n\u5F00\u59CB\u6478\u7D22\u80FD\u591F\u6740\u5BB3\u4E0D\u8001\u4E0D\u6B7B\u7684\u5979\u7684\u624B\u6BB5\u3002\n\n\u56E0\u6B64\uFF0C\u5411\u7956\u653F\u5448\u62A5\u5F00\u59CB\u5BFB\u627E\u4E0D\u8001\u4E0D\u6B7B\u7684\u7075\u836F\u3002\n\u4E1C\u6E21\u65E5\u672C\uFF0C\u5EFA\u7ACB\u4E86\u4E00\u5EA7\u6751\u843D\u3002\n\u5236\u9020\u7528\u4E8E\u4EBA\u4F53\u5B9E\u9A8C\u7684\u4EBA\u5076\uFF0C\u94FA\u8BBE\u6D88\u9664\u8BB0\u5FC6\u7684\u7ED3\u754C\u7B49\uFF0C\n\u8EAB\u4E3A\u9053\u58EB\u7684\u6280\u672F\u582A\u79F0\u4E00\u6D41\uFF0C\n\u4F46\u5728\u5979\u8FD9\u4EE3\u7EC8\u7A76\u672A\u80FD\u627E\u5230\u6740\u5BB3\u4E0D\u6B7B\u7684\u624B\u6BB5\uFF0C\n\u65E0\u5948\u53EA\u80FD\u6258\u4ED8\u7ED9\u4E0B\u4E00\u4EE3\u3002\n\u7ECF\u8FC7\u4E86\u8FD1\u4E24\u5343\u5E74\u7684\u94BB\u7814\uFF0C\u7531\u4E8E\u6751\u843D\u672C\u8EAB\u7684\u8870\u9000\uFF0C\n\u6700\u7EC8\u672A\u80FD\u5F97\u5230\u6740\u5BB3\u4E0D\u6B7B\u7684\u624B\u6BB5\u3002\n\n\u7136\u540E\u65F6\u5149\u518D\u6B21\u6D41\u901D\uFF0C\n\u65B9\u5DFF\u4F5C\u4E3A\u4ECE\u8005\u88AB\u53EC\u5524\uFF0C\n\u4EE5\u6751\u843D\u4E3A\u4E2D\u5FC3\u5F62\u6210\u4E86\u7279\u5F02\u70B9\u3002\n\n\u4E3A\u4E86\u610F\u56FE\u524D\u6765\u4FEE\u6B63\u7279\u5F02\u70B9\u7684\u96CF\u7F42\uFF0C\n\u51B3\u5FC3\u8FD9\u6B21\u4E00\u5B9A\u8981\u5B8C\u6210\u4E0D\u6B7B\u6740\u624B\u7684\u624B\u6BB5\n\u800C\u6697\u4E2D\u6D3B\u52A8\u2026\u2026\n\n\u4E0E\u5979\u5171\u5EA6\u4E00\u590F\u4E4B\u68A6\u3002",
    "condType": 9,
    "condValues": [
      5
    ],
    "condValue2": 0,
    "condValue": 0,
    "scriptXuyaoshiyongjsonchulidebianliang": ""
  },
  {
    "svtId": 1001400,
    "id": 7,
    "priority": 0,
    "condMessage": "",
    "comment": "\u901A\u5173\u67D0\u5173\u5361\u540E\u89E3\u9501",
    "condType": 1,
    "condValues": [
      911001401
    ],
    "condValue2": 0,
    "condValue": 0,
    "scriptXuyaoshiyongjsonchulidebianliang": ""
  },
  {

**Comment by hexstr** [comment]
是的，然后去找一个在线的json转yaml转换一下

**Comment by 1270207022** [comment]
@hexstr 好的谢谢

**Comment by hexstr** [comment]
这没有转换啊
