### ISSUE TITLE
剧情文本两个地方的从者名的替换小问题

### ISSUE THREAD

**Issue by SetsunaG** [nishuoshenme/FGOAssetsModifyTool#110]
虽然是小问题，姑且还是提一下吧，一个在近期的剧情活动中武则天的名字在剧情文本中没有替换成功，z在1.5里面是正常的
一个是杀生院Lily的，ScriptReplaceRules.json中没有对应的替换规则
我是用FGOAssetToolBox提取然后打包的，大佬有空康康 谢谢！

![JO0%NKVFE2TXHS_(I % 4R](https://github.com/hexstr/FGOAssetsModifyTool/assets/34825882/b32d05e7-cfcd-4cf9-8107-1d6949fcae18)
![image](https://github.com/hexstr/FGOAssetsModifyTool/assets/34825882/dd64d45d-7325-4c60-8460-c3b4d85c21fa)
![image](https://github.com/hexstr/FGOAssetsModifyTool/assets/34825882/b49487d8-0070-4c46-a84b-4e62d92cefc1)

**Comment by hexstr** [comment]
@SetsunaG 我忘记说明了，提取的时候要把ScriptReplaceRules.json放在同一个目录中不然不会生效的
比如X:\FGOAssetToolBox\data\Bilibili\ScriptReplaceRules.json

**Comment by hexstr** [comment]
@SetsunaG 不过我好像把加载路径写错了233

**Comment by SetsunaG** [comment]
好像是的，刚刚用新的提取工具提取，替换失效了，我之前一直用旧的提取的，但是旧的提取出来就出现上面武则天的在最近活动中没有成功的问题。杀生院Lily的那个在脚本里加上替换规则应该就没啥问题了

**Comment by hexstr** [comment]
更新了一下，现在替换规则文件重命名之后放置正确的话会加载
还有导出的文件要encoding utf16之后打包，模块才会加载

**Comment by SetsunaG** [comment]
谢谢！刚下载了最新的工具，打开弹了提示工具后，工具并没有打开

**Comment by hexstr** [comment]
@SetsunaG 应该是最近的commit又加了新的bug，等我更新一下

**Comment by hexstr** [comment]
可以更新了，还有默认导出的编码就是utf16这个不用管

**Comment by SetsunaG** [comment]
@hexstr 刚更新了，替换规则没有生效，不知道哪里出问题了，替换规则的路径是放对了的

**Comment by hexstr** [comment]
那我不管，反正我已经测试过了，可以把绘里濑改成绘里世(　ﾟ 3ﾟ)
![image](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/15a9b5ad-1ca8-4787-849c-8448669bfd49)
