### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by shatiaoaige** [nishuoshenme/FGOAssetsModifyTool#111]
#106  的完整日志https://pan.baidu.com/s/1o_nq0fHnB1zIZOYuNeM_3A 提取码:o5xw，没搞懂，怎么上传txt，度盘可以吗，前段时间被拉着去上了一个封闭式的培训班。没来得及及时反馈。真的很抱歉，还能麻烦大佬看一眼吗？

**Comment by hexstr** [comment]
![Screenshot_20230812-105125_Kiwi Browser](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/a5d1ff6b-1a0a-461a-a2f0-4c71927a47c8)
点这个图片按钮然后选择txt，等Upload ing结束就行

**Comment by shatiaoaige** [comment]
这个

**Comment by shatiaoaige** [comment]
[logcat_08-12-2023_10-13-35.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/12326335/logcat_08-12-2023_10-13-35.txt)
日志

**Comment by hexstr** [comment]
```
terminating with uncaught exception of type YAML::BadFile: bad file: /storage/emulated/0/Android/data/com.bilibili.fatego/files/Mod/Figure.yaml
```
在Mod文件夹创建一个空文件`Figure.yaml`

**Comment by hexstr** [comment]
> [logcat_08-12-2023_10-13-35.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/12326335/logcat_08-12-2023_10-13-35.txt) 日志

还有这条记得删掉，虽然日志文件应该不会包含什么敏感信息

**Comment by shatiaoaige** [comment]
[logcat_国服闪退.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/12326611/logcat_.txt)
[logcat_日服正常登陆.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/12326612/logcat_.txt)
原本国服和日服都会闪退，建立Figure.yaml后，日服可以进入，但国服依然闪退，分别抓取了两个 log.

**Comment by hexstr** [comment]
看来是无法捕获异常了，我更新了一下1.0.4你试试这个

**Comment by shatiaoaige** [comment]
感谢大佬，更新到1.0.4后两个服一切正常。没有闪退的现象了
另外，还有些小小的疑问，推荐日服替换的mstSkillDetail.yaml等文件在https://github.com/hexstr/FGOAssetsModifyTool/releases/tag/AssetDownload下的Assets中并不存在呀，搜索后发现了如图的
![Screenshot_2023-08-12-14-17-56-262_com android browser](https://github.com/hexstr/FGOAssetsModifyTool/assets/140603659/bbc1f059-7979-44e8-93d5-444abf1b4f2c)有相关名称的页面，
但是……呃，好像只是相关的代码？

**Comment by hexstr** [comment]
![image](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/bcc5fa31-ac22-4667-852b-90ecbaf93160)
