### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Loutroop** [nishuoshenme/FGOAssetsModifyTool#112]
很抱歉用一个issue的方式来建议，因为我找不到您的联系方式，请问能否使用此工具修改UI呢（是图片类型的）

**Comment by hexstr** [comment]
能吧，不过我没试过

**Comment by Loutroop** [comment]
那么目前使用这个工具能否做到这个？

**Comment by hexstr** [comment]
@loutroop 不能，如果你想替换图片然后重新覆盖文件，资源有完整性校验，自己会重新下载

**Comment by loutroop** [comment]
哎哟你干嘛

**Comment by Loutroop** [comment]
奇怪，这个mod把一些图片的UI改了呀
