### ISSUE TITLE
fgo日服版本2.78.1更新后资源替换上出现了些问题

### ISSUE THREAD

**Issue by yulongAI** [nishuoshenme/FGOAssetsModifyTool#113]
今天上午还好好的，更新后，下了很多安装包，但安装后都找不到arm64的文件夹，libmain.so失效了，强行替换会导致进不去游戏

**Comment by hexstr** [comment]
安装包有问题吧，去apkpure下载

**Comment by yulongAI** [comment]
确实是安装包的问题。apkpure上也下了，还是arm。刚刚在巴哈姆特上找到了，有arm64。

**Comment by yulongAI** [comment]
大佬，还有个问题，就是我学着你给的例子进行解包，然后再文本打包，却总是不成功，会出现乱码，而且这部分剧情就直接被跳过了，这是为什么。

**Comment by hexstr** [comment]
@yulongAI 你是怎么提取文本的？

**Comment by yulongAI** [comment]
就按照大佬的步骤，先解密，再用audioasset提取，就得到剧情文本了，我把其中一两句改成中文，之后打包好了放到Mod里，进游戏发现乱码，这部分剧情也被跳过了

**Comment by hexstr** [comment]
@yulongAI audioasset又是什么？AssetStudio？

**Comment by yulongAI** [comment]
对，就是这个，记错了

**Comment by hexstr** [comment]
@yulongAI 你还是看这个吧
https://github.com/hexstr/FGOAssetsModifyTool/blob/module/docs/HowToExtractAssets.md

在这里下载
https://github.com/hexstr/FGOAssets/releases/tag/FGOAssetToolBox

**Comment by yulongAI** [comment]
ScriptActionEncrypt/94/9408,这个asset没法用toolbox提取出来，会报错说value cannot be null（Parameter 'buffer
'）

**Comment by hexstr** [comment]
@yulongAI 可能是有什么变更，那还是手动打包吧，记得把文本utf16编码不然会乱码

**Comment by yulongAI** [comment]
成功了，感谢大佬，字体的话在文本里面换就行了嘛
