### ISSUE TITLE
关于字体包font

### ISSUE THREAD

**Issue by yulongAI** [nishuoshenme/FGOAssetsModifyTool#115]
替换的字体只有方正正黑吗，如果想用其他字体该怎么办

**Comment by hexstr** [comment]
@yulongAI 可以自己用unity打包一个assetbundle，unity版本是2020.3.34f1，打包的时候字体先重命名为FGO-Main-Font-Mod

**Comment by yulongAI** [comment]
我之前的思路也是这样，但打包出来没有生效，问题在于版本必须一致吗

**Comment by hexstr** [comment]
是的，但是不知道问题是不是在于这里

**Comment by yulongAI** [comment]
换了版本后，和之前的情况不一样了，想点进故事查看文本情况，然后loading很久，进去后文字还是没改变。是不是我打包步骤有问题，也可能是参数设置问题。我是先把字体文件.ttf导入，然后修改名称，再打包（没有改动参数），之后放到Mod里

**Comment by hexstr** [comment]
我不到啊，要不你自己看看日志

**Comment by yulongAI** [comment]
大佬，解决了，没想到这次栽在了 unity  f1c1和f1的不同上，还是版本的问题
