### ISSUE TITLE
国服更新后部分从者立绘替换失效

### ISSUE THREAD

**Issue by rurik13** [nishuoshenme/FGOAssetsModifyTool#116]
模拟器64位国服BGO在2.67.0版更新后，之前按照“How To Customize Pictures”页面通过Figure.yaml和Figure文件夹内png图片替换的从者立绘全部失效。其它替换，如数字.chara的从者立绘、master头像、技能名称、从者描述等替换均正常。尝试过模块的1.0.4、1.0.3、0.10.1、0.9.2、0.9.1等版本，前述部分从者立绘替换均未生效。请大佬看看该种替换能否恢复？谢谢

**Comment by hexstr** [comment]
![Screenshot_20230821-080413_Fate_GO](https://github.com/hexstr/FGOAssetsModifyTool/assets/28940831/ab97f19c-57a4-421d-b66a-d6c864cba404)
无法复现

**Comment by rurik13** [comment]
> 

感谢大佬回复，想再请教一下，您的截图的似乎是日服，这会不会是国服和日服不同导致的？有没有解决办法？谢谢

**Comment by hexstr** [comment]
@rurik13 不知道，不玩国服

**Comment by hexstr** [comment]
@rurik13 还有就是先拉一份完整日志

**Comment by rurik13** [comment]
[logcat_08-21-2023_09-04-25.txt](https://github.com/hexstr/FGOAssetsModifyTool/files/12390108/logcat_08-21-2023_09-04-25.txt)
不好意思我以前没拉过日志，请您看看这样的日志合不合用。

**Comment by hexstr** [comment]
`Figure.yaml`写错了，自己用editor改去
https://codebeautify.org/yaml-editor-online

**Comment by rurik13** [comment]
> `Figure.yaml`写错了，自己用editor改去 https://codebeautify.org/yaml-editor-online
多谢指点
