### ISSUE TITLE
部分文本在资源替换中找不到

### ISSUE THREAD

**Issue by Loutroop** [nishuoshenme/FGOAssetsModifyTool#118]
“友情点数”、“通常助战”类似的文本在此项目提供的资源替换中似乎找不到，请问它们被放在了哪里呢

**Comment by hexstr** [comment]
https://github.com/hexstr/FGOAssets/blob/master/LocalizationJpn.txt

**Comment by Loutroop** [comment]
额眼瞎了，抱歉
