### ISSUE TITLE
FGOAssetToolBox软件使用问题（闪退报错）

### ISSUE THREAD

**Issue by JeanneAlt** [nishuoshenme/FGOAssetsModifyTool#119]
解析masterdata之后，点击导出会闪退；
解析assetstorage之后，勾选一些文件后，可以正常下载但提取会报错（这个倒是可以下载bin文件后再用assetstudio来提取）
![image](https://github.com/hexstr/FGOAssetsModifyTool/assets/42638734/211c01e7-1e3d-4299-925d-f2704a814043)

**Comment by hexstr** [comment]
已修复
