### ISSUE TITLE
关于手机型号的兼容性问题

### ISSUE THREAD

**Issue by kevinadol** [nishuoshenme/FGOAssetsModifyTool#81]
请问大佬，这个解决方案理论上只要是安卓系统的手机 or 平板都可以使用吧？
最近打算苹果转安卓了，可能会买个三星的

**Comment by hexstr** [comment]
@kevinadol 能刷magisk就行

**Comment by hexstr** [comment]
@kevinadol 哦对，三星平板好像还有这个问题
https://github.com/hexstr/UnityFPSUnlocker/issues/31#issuecomment-1236297286
可以提前了解有没有解决方案
