### ISSUE TITLE
在BGO试图使用LocalizationJpn.txt闪退

### ISSUE THREAD

**Issue by GoldenMead** [nishuoshenme/FGOAssetsModifyTool#82]
使用别的替换都很正常，但一旦使用LocalizationJpn.txt就会出现闪退，模块版本0.92

**Comment by hexstr** [comment]
正常，接口不一样

**Comment by GoldenMead** [comment]
原来如此，多谢大佬解答了，我还以为是不是我这里有什么问题
那么使用1102.script后，在载入界面的从者职阶从英文又变回中文了是什么问题
