### ISSUE TITLE
请问这签要怎么弄啊

### ISSUE THREAD

**Issue by w66936989** [nishuoshenme/FGOAssetsModifyTool#83]
是哪个工具啊 [net6.0.7z](https://github.com/hexstr/FGOAssetsModifyTool/releases/download/AC/net6.0.7z)
3.05 MB
3 天之前
Source code
(zip)   是这个吗

**Comment by hexstr** [comment]
那个是加密解密工具

**Comment by w66936989** [comment]
> 

那签名怎么弄 就是验校不通过

**Comment by hexstr** [comment]
@w66936989 截图看看

**Comment by w66936989** [comment]
![QQ浏览器截图20221106003554](https://user-images.githubusercontent.com/112257525/200131197-e3a47903-fa61-4eeb-b746-354d41eb3555.png)
![QQ浏览器截图20221106003631](https://user-images.githubusercontent.com/112257525/200131201-9d6df9d2-1973-49c2-9ad6-e66406c90fb5.png)

**Comment by hexstr** [comment]
你这apk在哪下载的？不完整啊，运行库都没了

**Comment by w66936989** [comment]
塞不进去了 要签名了

**Comment by hexstr** [comment]
@w66936989 直接去apkpure下载xapk解压，把config.arm64_v8a.apk解压出来的lib文件夹复制到com.aniplex.fategrandorder.apk然后签名com.aniplex.fategrandorder.apk就行了啊

**Comment by hexstr** [comment]
给你整个一图流
解压工具用这个: https://m.apkpure.com/zarchiver/ru.zdevs.zarchiver
FGO的xapk在这里下载: https://m.apkpure.com/fate-grand-order/com.aniplex.fategrandorder/download?from=details
![end](https://user-images.githubusercontent.com/28940831/200317660-e28e391f-2602-4185-aeaf-e549ba406675.jpg)
