### ISSUE TITLE
国服反和谐时部分 新从者技能名资料 新礼装资料 变成日语

### ISSUE THREAD

**Issue by beotconoar** [nishuoshenme/FGOAssetsModifyTool#84]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/112243772/202485095-85cda368-c64b-43b7-92d7-2a263d6c4d6e.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/112243772/202485194-bdd28a08-6cc1-45b9-8f90-9c25270bdcc5.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/112243772/202485448-139df07e-189e-4f42-bb34-13ac0863a79e.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/112243772/202485571-b7421201-f7a3-4277-8bae-daf89468714c.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/112243772/202486028-db84ab5f-1114-4426-aefc-b893d3e778b2.png">
骑龙娘只有资料是日语

**Comment by hexstr** [comment]
？你玩国服干嘛要下载给日服推荐的文件，都删了就行

**Comment by beotconoar** [comment]
> ？你玩国服干嘛要下载给日服推荐的文件，都删了就行

因为之前那次技能名和资料里的真名也被河蟹了，吸血改成汲取之类的

**Comment by hexstr** [comment]
@beotconoar 那就只把文件中新从者的部分删了，注意yaml格式就行
