### ISSUE TITLE
怎样将国服的最新的剧情文本打包出来？自己尝试搞了一晚没弄明白

### ISSUE THREAD

**Issue by SetsunaG** [nishuoshenme/FGOAssetsModifyTool#85]
看好久没同步更新国服的剧情文本了，玩的是国服，想要这个是因为有了新的替换规则后的剧情文本可以把剧情中和谐掉的名字反和谐了，自己尝试了一下去解，但是没整明白，如果会自己解包出新剧情文本并用新规则替换反和谐，也就能自力更生不用麻烦大佬更新了

**Comment by hexstr** [comment]
把所有的`Script`开头的`.bin`文件全部提取出来然后`解密剧情文本`，把解密后的`.txt`放在一个文件夹就行了。
你可以用这个打包和解包
https://github.com/hexstr/TextBundle/releases
拿打包好了的`.script`拆开看

**Comment by SetsunaG** [comment]
这个打包解包工具我运行后只要一输入就闪退，是缺少什么运行环境吗

**Comment by hexstr** [comment]
哦那个不一样，那个要从cmd输入命令。不会用就参考[这篇](https://zhuanlan.zhihu.com/p/370034641)或者自己搜

![image](https://user-images.githubusercontent.com/28940831/208922711-391c5940-c9ab-49a0-8462-933d9cdebc25.png)

**Comment by SetsunaG** [comment]
原来是要用cmd啊 我以为是这个打包工具里直接输入命令...哈哈

**Comment by SetsunaG** [comment]
打包解包 包括离线数据包解密这些都搞了一遍了，现在还有个问题就是这个Script开头的.bin文件这个是用到AssetStudio去提取对吗？如果是的话离线包里bin文件太多了AssetStudio读取的时候爆了我的内存

**Comment by hexstr** [comment]
@SetsunaG 只提取剧情文本就行了啊

**Comment by SetsunaG** [comment]
我解密出来的bin文件名都是这样的，完全分不出剧情文本是哪些 是我哪里搞错了吗
![image](https://user-images.githubusercontent.com/34825882/208935707-84a309d4-968e-4194-b69f-f24472e3799d.png)

**Comment by hexstr** [comment]
@SetsunaG 解密AssetStorage.txt打开AssetName.json

**Comment by SetsunaG** [comment]
前面的都搞定了，真的很感谢大佬耐心指教只剩下最后一个问题了，就是我加载替换规则后打包剧情文本，发现替换的没有生效，这里漏了什么吗

**Comment by hexstr** [comment]
@SetsunaG 我都忘了当时在bgo测试过文本替换没有，你把我打包的扔进去看看有没有效果

**Comment by SetsunaG** [comment]
有的 之前大佬打包的剧情文本我都有在用

**Comment by hexstr** [comment]
那我也不知道什么问题，自己看日志，或者先用我刚刚打包的

**Comment by SetsunaG** [comment]
我把ScriptReplaceRules.json这个丢进net6.0文件夹里然后用FGOAssetsModifyTool折行加载替换规则，然后再打包文件，这里步骤会有错或者遗漏的吗

**Comment by hexstr** [comment]
用这个吧，虽然是半成品但是提取素材也够用了
~~https://share.gugugu.pp.ua/api/file/KfW2BW~~
多加了一行判断，用这个
https://share.gugugu.pp.ua/api/file/jKrJHy
用法在这儿
https://github.com/hexstr/FGOAssetsModifyTool/blob/module/docs/HowToExtractAssets.md
