### ISSUE TITLE
国服版本更新后立绘替换失效

### ISSUE THREAD

**Issue by SkylineKID** [nishuoshenme/FGOAssetsModifyTool#86]
雷电9模拟器9.0.29版，游戏版本2.57.0，
安装了最新的0.9.3版插件，不安装x86loader的情况下全部无法生效替换，
安装x86loader的情况下仅窄边框立绘生效

**Comment by MikuMikuMi520** [comment]
同上   不过我是9.0.25   且闪退

**Comment by Youxikong** [comment]
客户端版本2.57.0，无法替换立绘。

**Comment by Shwork28** [comment]
同上我是9.0.19

**Comment by fate2022** [comment]
同上我也是9.0.19
