### ISSUE TITLE
现在是否还支持替换主页立绘功能

### ISSUE THREAD

**Issue by lxm0130** [nishuoshenme/FGOAssetsModifyTool#89]
我在预览图中看到大佬替换了主页的立绘，不知道现在的版本是否还支持。
解包了CharaFigure提取出了立绘，看着像是个人空间的立绘。
立绘命名的规则是从者id+012对应123破，还有一个剪影图，我提取出来后自己ps换了立绘,并自己在Mod/Figure/下建了CharaFigure文件夹，用对应的命名规则放进去后也没能生效，直接放在Figure文件夹下也试过，也没生效。
所以不知道现在的版本是否还支持替换主页立绘的功能，如果能够支持还请大佬将替换方法分享一下，真心感谢！

**Comment by hexstr** [comment]
不支持，是本来就不支持哦，艾蕾的那个是通过修改从者id实现的
