### ISSUE TITLE
Re encrypt cfb1d36393fd67385e046b084b7cf7ed

### ISSUE THREAD

**Issue by Darkmet98** [nishuoshenme/FGOAssetsModifyTool#91]
Hi, sorry for speaking in English because I don't know Chinese, but I have a little Issue with this file, how I can reencrypt the file after adding some modifications for avoiding the game redownloading the file?

I've tried to add the function doing the reverse process without success

```Cs
 public string CatGame8(string str)
        {
		var data = Encoding.UTF8.GetBytes(str);
		var array = CatHomeMain(data, stageData, stageTop, true);
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = (byte)~array[i];
            }
            return System.Convert.ToBase64String(array);
        }

//I've modified the cathomemain for forcing the Bzip2 compression
```
Any toughs about this?

Thanks.

**Comment by hexstr** [comment]
Checkout this repo maybe it can help you.
https://github.com/rayshift/translatefgo
