### ISSUE TITLE
关于国服礼装头像的MOD

### ISSUE THREAD

**Issue by kevinadol** [nishuoshenme/FGOAssetsModifyTool#92]
大佬请问一下，国服礼装头像如何修改？目前打上MOD之后，其他的都成功反和谐了，但是礼装头像还是大头贴

**Comment by hexstr** [comment]
参见#71

**Comment by kevinadol** [comment]
请问接口指的是什么，我也试着找找看

**Comment by hexstr** [comment]
@kevinadol 加载礼装头像的函数。除了这个我甚至连礼装头像的图片文件都没找到在哪

**Comment by kevinadol** [comment]
哦指的是API啊，我回头找时间看看

**Comment by kevinadol** [comment]
按理说这个头像文件应该是也存在本地的
