### ISSUE TITLE
手机版每次重启闪退怎么解决

### ISSUE THREAD

**Issue by w46836226** [nishuoshenme/FGOAssetsModifyTool#93]
手机版2b1b0ee6文件每次重启就自动下回来了，每次重启都得手动删一遍。模拟器版2b1b0ee6初始删一次就行了之后文件存在也不会闪退。有什么解决方法嘛

**Comment by w46836226** [comment]
试了一下刷回9.4的手机版模块就不会闪退了。用10.0之后的通用模块手机版就得每次启动bgo前都要手动删除一次2b1b0ee6文件才行了。

**Comment by hexstr** [comment]
@w46836226 bgo就用旧版，或者提供一下日志

**Comment by w46836226** [comment]
不会抓日志，麻烦大佬了😂

**Comment by hexstr** [comment]
@w46836226 还有就是bgo不支持`LocalizationJpn.txt`你要把这个文件删了

**Comment by w46836226** [comment]
没装这个文件。10.0之后的也只有手机版才出现这个问题，目前先用9.4的手机专用版模块了。感谢大佬。
![Screenshot_2023-01-29-10-08-16-282_com vphonegaga titan](https://user-images.githubusercontent.com/123843443/215300508-47861e5f-effc-43ca-90bf-e6734d9445ea.jpg)
