### ISSUE TITLE
想问大佬在最新雷电模拟器下真的能用这个工具吗？

### ISSUE THREAD

**Issue by ft2182910** [nishuoshenme/FGOAssetsModifyTool#95]
看别人教程只要版本高于9.0.19都没办安装Magisk，也就没办法启动模块，还是有其他方法？
我自己试过在最新版本装Magisk需要系统分区是读写，但默认是只读，而我没办法改成读写说要root，但我已经root了……

**Comment by hexstr** [comment]
![Snipaste_2023-02-08_18-38-39](https://user-images.githubusercontent.com/28940831/217506760-2a351188-53af-4f65-8d77-4b45c561dbf8.jpg)
也可以找找有没有人打包模拟器镜像，就是整合包那种

**Comment by ft2182910** [comment]
明白了，原来是这里调的，非常感谢。
