### ISSUE TITLE
自行修改 Master 数据 （mstSvt 等等）

### ISSUE THREAD

**Issue by ghost** [nishuoshenme/FGOAssetsModifyTool#96]
我这边用了`FGOAssetsModifyTool`按了 `3` 然后 `8` 之后能给出很多有趣的数据（从者，技能等等）
当我自己尝试修改好了之后，我发现我不知如何把这些数据打包然后放回游戏里
然后当我发现FGOAssetReplace之后，我尝试把修改后的文件 (e.g. `mstSvt`) 放到 `Mod` 文件夹了
但是我发现FGOAssetReplace只接受为改名而设的`.yaml`格式的文件

请求问一下大神，如果我想修改 Master以内之类的数据 ，我该如何下手？或者是FGOAssetReplace以后会不会有能直接接受并且替换Master内的`json`格式的文件？

**Comment by hexstr** [comment]
@Axovur 1）游戏内的格式是MsgPack，工具导出为json是方便使用，不代表你能直接替换进游戏
2）不会支持

**Comment by ghost** [comment]
感谢大神的回复🙏

请问如果我想要达到您的境界（能做出像`FGOAssetsModifyTool`的工具和`Magisk`的模块），我要学习些什么（需要哪些知识），和我该从哪里开始？

**Comment by hexstr** [comment]
@Axovur 别问我，问就是计算机专业知识学一遍
