### ISSUE TITLE
日服领取任务奖励时卡死

### ISSUE THREAD

**Issue by uoyh** [nishuoshenme/FGOAssetsModifyTool#99]
![photo_2023-05-29](https://github.com/hexstr/FGOAssetsModifyTool/assets/104709591/77112678-a1b2-4150-8f54-92c9eb138f32)

如图，一直Loading，约两周前第一次出现，关闭模块后正常

没替换UI文本`LocalizationJpn.txt`，不过替换后依旧出现，用的是 https://github.com/hexstr/FGOAssetsModifyTool/releases/tag/AssetDownload 的最新`LocalizationJpn.txt`

**Comment by hexstr** [comment]
这是哪个版本？

**Comment by uoyh** [comment]
乌龙了，最新的模块下载好后没装上，我以为装上了。
